spring:
    cloud:
        config:
            name: application  # This tells it to look for 'application-prod.yml'
            label: mailing
            profile: prod
            discovery:
                enabled: false
            fail-fast: true
            retry:
                initial-interval: 1000
                max-attempts: 6
                max-interval: 2000
                multiplier: 1.1
            username: ${SPRING_CLOUD_CONFIG_USERNAME}
            password: ${SPRING_CLOUD_CONFIG_PASSWORD}
        discovery:
            enabled: true